=== finos/datahelix/schemas/src/main/resources/profileschema/0.1/datahelix.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://scottlogic.com/datahelix.json",
  "definitions": {

    "schemaVersion": {
      "type": "string",
      "title": "The version of the DataHelix profile schema",
      "pattern": "^[0-9]+[.][0-9]+$"
    },

    "temporal": {
      "type": "object",
      "additionalProperties": false,
      "required": ["date"],
      "properties": {
        "date": {
          "type": "string",
          "title": "an ISO 8610 compatible string denoting a date and time",
          "pattern": "^[0-9]{4}-([0][0-9]|[1][0-2])-([0-2][0-9]|3[01])T([0-1][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9][.][0-9]{3}$"
        }
      }
    },

    "fieldName": {
      "title": "The name of a field to generate data for",
      "type": "object",
      "additionalProperties": false,
      "required": ["name"],
      "properties": {
        "name": {"type": "string"}
      }
    },

    "constraint": {
      "oneOf": [
        {
          "$ref": "#/definitions/grammaticalConstraint"
        },
        {
          "$ref": "#/definitions/dataConstraint"
        }
      ]
    },

    "grammaticalConstraint": {
      "oneOf": [
        {
          "$ref": "#/definitions/notConstraint"
        },
        {
          "$ref": "#/definitions/anyOfConstraint"
        },
        {
          "$ref": "#/definitions/allOfConstraint"
        },
        {
          "$ref": "#/definitions/ifConstraint"
        }
      ]
    },

    "dataConstraint": {
      "type": "object",
      "additionalProperties": false,
      "required": ["field", "is"],
      "properties": {
        "field": {"type": "string"},
        "is": {
          "enum": [
            "ofType", "equalTo", "aValid", "inSet",
            "formattedAs", "matchingRegex", "containingRegex", "ofLength", "longerThan", "shorterThan",
            "null",
            "greaterThan", "lessThan", "greaterThanOrEqualTo", "lessThanOrEqualTo", "granularTo"
          ]
        }
      },
      "anyOf": [
        {
          "if": {
            "properties": {"is": {"const": "equalTo"}}
          },
          "then": {
            "properties": {"value": {}}
          }
        },
        {
          "if": {
            "properties": {"is": {"const": "ofType"}}
          },
          "then": {
            "properties": {"value": {"enum": ["decimal", "integer", "string", "temporal"]}}
          }
        },
        {
          "if": {
            "properties": {"is": {"const": "inSet"}}
          },
          "then": {
            "properties": {"values": {"type": "array"}}
          }
        },
        {
          "if": {
            "properties": {"is": {"const": "null"}}
          },
          "then": {
            "properties": {"not": {}}
          }
        },
        {
          "if": {
            "properties": {"is": {"const": "formattedAs"}}
          },
          "then": {
            "properties": {"value": {"pattern": "^%.+$"}}
          }
        },
        {
          "if": {
            "properties": {"is": {"enum": ["matchingRegex", "containingRegex"]}}
          },
          "then": {
            "properties": {"value": {"type": "string"}}
          }
        },
        {
          "if": {
            "properties": {
              "is": {
                "enum": [
                  "shorterThan", "longerThan", "greaterThan", "lessThan", "greaterThanOrEqualTo", "lessThanOrEqualTo", "granularTo",
                  "ofLength"
                ]
              }
            }
          },
          "then": {
            "properties": {"value": {"type": "number"}}
          }
        },
        {
          "if": {
            "properties": {"is": {"const": "aValid"}}
          },
          "then": {
            "properties": {"value": {"pattern": "^ISIN$"}}
          }
        }
      ]
    },

    "notConstraint": {
      "type": "object",
      "additionalProperties": false,
      "required": ["not"],
      "properties": {
        "not": {"$ref": "#/definitions/constraint"}
      }
    },

    "anyOfConstraint": {
      "type": "object",
      "additionalProperties": false,
      "required": ["anyOf"],
      "properties": {
        "anyOf": {
          "type": "array",
          "minItems": 2,
          "items": {
            "$ref": "#/definitions/constraint"
          }
        }
      }
    },

    "allOfConstraint": {
      "type": "object",
      "additionalProperties": false,
      "required": ["allOf"],
      "properties": {
        "allOf": {
          "type": "array",
          "minItems": 2,
          "items": {
            "$ref": "#/definitions/constraint"
          }
        }
      }
    },

    "ifConstraint": {
      "type": "object",
      "required": ["if", "then"],
      "properties": {
        "if": {
          "$ref": "#/definitions/constraint"
        },
        "then": {
          "$ref": "#/definitions/constraint"
        },
        "else": {
          "$ref": "#/definitions/constraint"
        }
      }
    }
  },

  "type": "object",
  "additionalProperties": false,
  "required": ["schemaVersion", "fields", "rules"],
  "title": "The Scott Logic DataHelix Profile Schema",
  "properties": {

    "schemaVersion": {
      "$ref": "#/definitions/schemaVersion"
    },

    "description": {
      "type": "string",
      "title": "A description of what data the profile is modelling"
    },

    "fields": {
      "type": "array",
      "minItems": 1,
      "uniqueItems": true,
      "title": "Defines the fields that data will be produced for. field names must begin with an alphabetic character.",
      "items": {
        "$ref": "#/definitions/fieldName"
      }
    },

    "rules": {
      "type": "array",
      "minItems": 1,
      "title": "The Rules defining the data to be output",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": ["constraints"],
        "title": "A set of Rule objects.",
        "properties": {
          "rule": {
            "type": "string",
            "title": "A collection of constraints. Test case generation revolves around rules, in that the generator will output a separate dataset for each rule, wherein each row violates the rule in a different way."
          },
          "constraints": {
            "type": "array",
            "minItems": 1,
            "items": {"$ref": "#/definitions/constraint"}
          }
        }
      }
    }
  }
}

=== finos/datahelix/profile/src/test/resources/test-profiles/valid/constraints-nested-inside-anyof.json
{
  "schemaVersion": "0.2",
  "description": "profile description",
  "rules": [
    {
      "rule": "rule 1",
      "constraints": [
        {
          "anyOf": [
            {
              "field": "field1",
              "is": "formattedAs",
              "value": "%ggg"
            },
            {
              "field": "field1",
              "is": "shorterThan",
              "value": 19
            }
          ]
        }
      ]
    }
  ],
  "fields": [
    {
      "name": "field1"
    }
  ]
}

=== finos/datahelix/profile/src/test/resources/test-profiles/valid/constraints-nested-inside-allof.json
{
  "schemaVersion": "0.2",
  "description": "profile description",
  "rules": [
    {
      "rule": "rule 1",
      "constraints": [
        {
          "allOf": [
            {
              "field": "field1",
              "is": "ofType",
              "value": "string"
            },
            {
              "field": "field2",
              "is": "greaterThan",
              "value": 43
            }
          ]
        }
      ]
    }
  ],
  "fields": [
    {
      "name": "field1"
    }
  ]
}

=== finos/datahelix/generator/resources/serialisation-only-tests/simple-two-partitions/profile.json
{
	"schemaVersion": "v3",
	"description": "TestProfile1",
	"fields":
	[
		{ "name": "Level" },
		{ "name": "Type" },
		{ "name": "Identifier" },
		{ "name": "Event" }
	],
	"rules": [{
		"rule": "Level",
		"constraints": [{
			"field": "Level",
			"is": "inSet",
			"values": [
				"First",
				"Second",
				"Third",
				"Fourth",
				"Fifth"
			]
		},{
			"not": {
				"field": "Level",
				"is": "null"
			}
		},{
			"if": {
				"allOf": [{
					"field": "Type",
					"is": "inSet",
					"values": [
						"A",
						"B"
					]
				}]
			},
			"then": {
				"allOf": [{
					"field": "Level",
					"is": "inSet",
					"values": [
						"Second",
						"Third"
					]
				}]
			}
		},{
			"if": {
				"allOf": [{
					"field": "Type",
					"is": "inSet",
					"values": [
						"C"
					]
				}]
			},
			"then": {
				"allOf": [{
					"field": "Level",
					"is": "equalTo",
					"value": "First"
				}]
			}
		}]
	},{
		"rule": "Type",
		"constraints": [{
			"field": "Type",
			"is": "inSet",
			"values": [
				"A",
				"B",
				"C",
				"D",
				"E"
			]
		}]
	},{
		"rule": "Identifier",
		"constraints": [{
			"field": "Identifier",
			"is": "inSet",
			"values": [
				"EventA",
				"EventB",
				"EventC"
			]
		}]
	},{
		"rule": "Event",
		"constraints": [{
			"field": "Event",
			"is": "ofType",
			"value": "string"
		},{
			"field": "Event",
			"is": "shorterThan",
			"value": 10
		},{
			"if": {
				"allOf": [{
					"field": "Identifier",
					"is": "equalTo",
					"value": "EventB"
				}]
			},
			"then": {
				"field": "Event",
				"is": "shorterThan",
				"value": 20
			}
		}]
	}]
}
